[package]
name = "emtm"
version = "0.1.0"
authors = ["Miguel Chan <vvchan@outlook.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.0", features = ["mysql"] }
dotenv = "0.10"
rocket = "0.4.0"

